name: "Config"

inputs:
  config-path:
    description: "Config path"
    required: true
  environment:
    description: "Environment"
    required: true

outputs:
  result:
    description: "Result"
    value: ${{ steps.process-config.outputs.result }}

runs:
  using: "composite"
  steps:
    - id: process-config
      uses: actions/github-script@v7
      with:
        script: |
          const fs = require('fs');
          const configPath = '${{ inputs.config-path }}';
          const config = fs.readFileSync(configPath, 'utf8');
          const environmentVariablesJson = JSON.parse(config)['${{ inputs.environment }}'];

          for (const [key, value] of Object.entries(environmentVariablesJson)) {
            core.exportVariable(key, value);
          }
