name: "Config"

inputs:
  config-path:
    description: "Config path"
    required: true

outputs:
  result:
    description: "Result"
    value: ${{ steps.step1.outputs.result }}

runs:
  using: "composite"
  steps:
    - id: step1
      run: echo "result=$(jq -c . <  ${{ inputs.config-path }})" >> $GITHUB_OUTPUT
      shell: bash
