name: "IO"

inputs:
  number:
    description: "Number"
    required: true
    default: "88"

outputs:
  result:
    description: "Result"
    value: ${{ steps.step1.outputs.result }}
runs:
  using: "composite"
  steps:
    - id: step1
      run: echo "result=${{ inputs.number }} Given" >> $GITHUB_OUTPUT
      shell: bash
