name: My GHA experiment
run-name: ${{ github.actor }} is testing out GitHub Actions

on: push

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository (Job)
        uses: actions/checkout@v4
      - name: Use local json-config
        id: hello
        uses: ./.github/actions/json-config
        with:
          config-path: ./config.json
          environment: staging
      - name: Get the env variables
        run: env | grep token
      # - uses: actions/setup-python@v4
      #   with:
      #     python-version: '3.x'
      # - uses: jannekem/run-python-script-action@v1
      #   with:
      #     script: |
      #       import os
      #       print("Environment variables:")
      #       for name, value in os.environ.items():
      #         print("{0}: {1}".format(name, value))

  # job2:
  #   runs-on: ubuntu-latest
  #   steps:
  #     # This step checks out a copy of your repository.
  #     - name: My first step - check out repository
  #       uses: actions/checkout@v4
  #     - name: Use local hello-world-action
  #       id: hello
  #       uses: ./.github/actions/hello-world-action
  #     - name: Get the hello-world-action outputs
  #       run: echo "The random number is ${{ steps.hello.outputs.random-number }}."
  #     - name: Use local io-action
  #       id: io
  #       uses: ./.github/actions/io
  #       # with:
  #       #   number: 42
  #     - name: Get the io-action outputs
  #       run: echo "The result is ${{ steps.io.outputs.result }}."
